2022/08/21 23:48:31 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: lijb, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "lijb.test.ru"
2022/08/21 23:48:31 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: 2022-08-22T02:48:31+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/lijb/var/log)" while reading upstream, client: 172.18.0.1, server: lijb, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "lijb.test.ru"
2022/08/21 23:54:29 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://lijb.test.ru/"" at /lijb/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: lijb, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "lijb.test.ru"
2022/08/21 23:54:30 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://lijb.test.ru/favicon.ico" (from "https://lijb.test.ru/")" at /lijb/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: lijb, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "lijb.test.ru", referrer: "https://lijb.test.ru/"
2022/08/23 00:04:53 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: lijb, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "lijb"
2022/08/23 00:09:54 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: lijb, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "lijb"
